### ISSUE TITLE
less编辑是否支持livestyle插件，实现浏览器和编辑器双向同步

### ISSUE THREAD

**Issue by isence** [Tencent/tmt-workflow#111]
之前写本地项目，会用livestyle插件浏览器和编辑器双向同步，现在使用tmt工作流，想问下是否也支持

**Comment by littledu** [comment]
双向同步需要安装浏览器插件+编辑器插件，跟一个 `流程` 不一样。

如果用 livestyle 的说法，那 tmt-workflow 支持单向同步：自动刷新
