### ISSUE TITLE
关于 REM 解决方案自定义的问题

### ISSUE THREAD

**Issue by soyaine** [Tencent/tmt-workflow#114]
在 [Wiki](https://github.com/Tencent/tmt-workflow/wiki/%E2%92%94-REM-%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88) 中提到：
> tmt-workflow 基准值约定   
> <html> 根节点默认 font-size = 20px    
> 
> 视觉稿默认宽度为 375px（即 iPhone 6 尺寸） 

想请问此处的视觉稿默认宽度能否自定义修改，以方便开发电脑屏幕访问的网页（宽度为 1920px）？

**Comment by hzlzh** [comment]
PC 的项目建议关闭 rem 方案，直接用 px 开发。
如果要定制基准值，参看这里 https://github.com/Tencent/tmt-workflow/issues/93
