### ISSUE TITLE
关于新增文件的存放位置

### ISSUE THREAD

**Issue by xzfd1010** [Tencent/tmt-workflow#115]
如果需要在css中引入字体文件，字体文件放在css目录下，build_dev时会自动删除，请问该如何解决？谢谢。
另外发现引入一些普通的css库，比如normalize.css或者jquery-ui.min.css也会在编译的过程中删除掉，是必须都改成style-*.less的形式么？

**Comment by csdudu** [comment]
我今天刚试用发现：
1、iconfont的几种字体文件，只能放到src/media/font目录。其它目录都会检查后缀的。比如src/html目录下只容纳.html文件。
2、.css文件都可以放在src/css目录下，开发模式下会自动拷贝到dev/css，没发现你说的删除的情况。

**Comment by hzlzh** [comment]
1. media                     // 存放媒体文件，如 bgm.mp3 abc.font 1.mp4 等

2. style-*.less 是出口文件，你把库放进 /css/ 文件夹下，改成 jquery.less 即可
