### ISSUE TITLE
呼唤以下新功能！

### ISSUE THREAD

**Issue by csdudu** [Tencent/tmt-workflow#116]
1、打包zip文件能否自定义命名，比如增加内容描述、时间等。
2、目前发布文件后，根目录只能预览文件列表，能否为所有HTML文件增加一个描述项？在右侧增加一个模拟手机外观的预览框？---我看到有朋友实现了这个功能。
![image](https://user-images.githubusercontent.com/5706088/28498084-da90c670-6fc8-11e7-9dc8-b4b7d6afb495.png)

3、增加一个总项目列表
![2](https://user-images.githubusercontent.com/5706088/28498086-dc9c6f32-6fc8-11e7-86fb-97c237d4aedf.png)

4、我还有一个疑问，新建项目时，能否包含自己常用的文件结构及文件，比如建立src/media/font这样的字体包含路径？我目前都是先拷贝目录，再使用“打开项目”功能来做。

**Comment by hzlzh** [comment]
感谢你的建议。
1. zip 是一个低频操作，每次 WeFlow 都会生成是覆盖之前的 dist.zip，直接使用最新的即可。

2. 我们目前的交接方式是文件列表，觉得这样预览配合 Chrome 的 mobile 模式预览很够用了

3. 总项目列表目前是直接在 WeFlow 界面上查看的，如果要生成需要考虑存放在哪的问题。

4. 可以的，把你想要的项目结构覆盖到 `/WeFlow.app/Contents/Resources/app/templates/project.zip`
![image](https://user-images.githubusercontent.com/1049575/29064718-817eb410-7bef-11e7-81f4-c8bfb3ce68d5.png)
