### ISSUE TITLE
使用的 gulp-usemin2 无法压缩 css 文件

### ISSUE THREAD

**Issue by SuperAL** [Tencent/tmt-workflow#117]
tmt-workflow 中使用的  [gulp-usemin2](https://github.com/pursual/gulp-usemin) ，设置 cssmin 的方法为 minifyCSS（gulp-cssnano）或 cleanCSS（gulp-clean-css）都会导致无法生成最终的 css 文件，html 有改动，但就是 css 文件没有出现，希望技术大神可以帮忙看看这个问题~

**Comment by hzlzh** [comment]
gulp-usemin2 是你的 fork 版本吧，你扩展了什么功能尝试能否直接用原版的接口来完成。
via https://github.com/zont/gulp-usemin
