### ISSUE TITLE
CSS Sprite

### ISSUE THREAD

**Issue by lilyneaoer** [Tencent/tmt-workflow#121]
移动端项目，CSS Sprite合并雪碧图图标，生成代码之后，在安卓环境，图标无法正常显示。会不会是因为单位的问题，我用的是rem，但生成之后的雪碧图位置单位还是px，求解？

**Comment by hzlzh** [comment]
rem 和 雪碧图不要同事使用，否则会有毛边的问题。
解决方案：把所有 slice 图都丢到 img 目录里，不用雪碧图方案了，然后可以开启 HTTP 2.0 的支持，加速并发请求。

参考：
https://segmentfault.com/a/1190000008910038
https://www.w3ctech.com/topic/1563

**Comment by lilyneaoer** [comment]
谢谢，我试试看
