### ISSUE TITLE
关于目录结构

### ISSUE THREAD

**Issue by xzfd1010** [Tencent/tmt-workflow#122]
你好，我在使用这个流程的时候按照推荐的目录结构将html文件都放在html文件夹中。
但是运维/后台说在配置nginx的时候，需要将index.html放在最外面，否则就要将html文件夹作为根目录。
我并不是很了解他们的问题出在哪里，但是想问下楼主有解决这种问题的经验么？

**Comment by hzlzh** [comment]
你可以根据自身项目特点把 html 文件放到 ../html/ 的上一级，注意 js css 引用路径就好了。
参看这里：https://github.com/Tencent/tmt-workflow/blob/master/_tasks/TaskBuildDev.js#L41

**Comment by xzfd1010** [comment]
好的，谢谢！
