### ISSUE TITLE
px -> rem: 视觉稿默认宽度为什么不是 750px?

### ISSUE THREAD

**Issue by luxiaowu** [Tencent/tmt-workflow#123]
如果使用 `375px`, 需要从视觉稿量取像素除以2，很不方便

另：在使用 `px`-> `rem` 转换后，**部分安卓机器** 和 **windows wechat 浏览器** 识别区域有问题（项目中用到 `jQuery UI` 实例 `Draggable` 和 `Droppable`）去掉 REM适配 恢复正常

项目地址：http://game.yuemia.com/static/move/html/index.html

**Comment by hzlzh** [comment]
1. 设计师的尺寸一般是像素尺寸，我们前端遇到二倍或者三倍屏幕要除2 除3 是很正常的，我们一直是这样去写的

2. 如果用到了其他的外部库，可以把外部库的 css 改成 less 之后 import 进去。

**Comment by luxiaowu** [comment]
哈哈，我是看到 小程序使用 rpx 作为单位

> 新增了尺寸单位。在写 CSS 样式时，开发者需要考虑到手机设备的屏幕会有不同的宽度和设备像素比，采用一些技巧来换算一些像素单位。WXSS 在底层支持新的尺寸单位 rpx ，开发者可以免去换算的烦恼，只要交给小程序底层来换算即可，由于换算采用的浮点数运算，所以运算结果会和预期结果有一点点偏差。  
 rpx（responsive pixel）: 可以根据屏幕宽度进行自适应。规定屏幕宽为750rpx。如在 iPhone6 上，屏幕宽度为375px，共有750个物理像素，则750rpx = 375px = 750物理像素，1rpx = 0.5px = 1物理像素。
**建议：** 开发微信小程序时设计师可以用 iPhone6 作为视觉稿的标准。

我是不是太懒了，什么都想用现成的！[笑cry]
