### ISSUE TITLE
EJS include 无效

### ISSUE THREAD

**Issue by Aaaaaashu** [Tencent/tmt-workflow#128]
当前 html 的目录结构
```
├── common
│   ├── footer.ejs
│   └── navbar.ejs
├── index.html
└── doc.html
```

当在 index.html 中 `<% include common/navbar %>` 可以编译通过
但在 doc.html 中 `<% include common/navbar %>` 却处于一直编译中，无法显示该 navbar 代码片段。

**Comment by Aaaaaashu** [comment]
发现由于 `<% include common/navbar %>`  中引用 img 路径问题导致。

原来的 img 路径引用:
```
<img class="navbar-logo" src="../../img/logo.svg" alt="imtoken logo" />
```

修改后的路径：
```
<img class="navbar-logo" src="../img/logo.svg" alt="imtoken logo" />
```

奇怪的地方是，如果是路径错误的话，但 index.html 却可以工作。
另外 includes ejs 模板后，有效路径是根据当前 html 页面作为相对路径。

// 如果编译阶段，有对应的报错提示就更好了。

**Comment by littledu** [comment]
这里的 `include` 相当于把代码片段粘贴到对应位置，所以是相对于 `父级` 的，也就是所存在的 html 页面。

至于图片路径引用错误理论来讲应该是在打开页面运行时才发现，对编译阶段应该是不影响的，可能会有的影响可能是开启了 `reversion` 功能，需要修改 logo.svg 的名字因为路径错误没找到。
