### ISSUE TITLE
npm install 报错

### ISSUE THREAD

**Issue by houyaowei** [Tencent/tmt-workflow#129]
node版本：v9.11.1
具体错误消息
<img width="1111" alt="2018-05-02 10 01 58" src="https://user-images.githubusercontent.com/3080429/39501912-174734cc-4df0-11e8-8af3-b39e7f7c1037.png">
<img width="1107" alt="2018-05-02 10 02 12" src="https://user-images.githubusercontent.com/3080429/39501917-1bcce88e-4df0-11e8-8beb-476bb5c1cdf9.png">
<img width="1110" alt="2018-05-02 10 02 25" src="https://user-images.githubusercontent.com/3080429/39501918-1dff0d30-4df0-11e8-8ea2-dde563db6ef9.png">
<img width="1095" alt="2018-05-02 10 02 34" src="https://user-images.githubusercontent.com/3080429/39501919-1fea1cd4-4df0-11e8-9694-19d0d000ebf6.png">
<img width="740" alt="2018-05-02 10 02 41" src="https://user-images.githubusercontent.com/3080429/39501926-2524539a-4df0-11e8-856c-cddb0ce6bb1f.png">

麻烦在百忙中给指导一下。谢谢

**Comment by littledu** [comment]
明天会更新一版解决这个问题。

**Comment by hzlzh** [comment]
@houyaowei 不知问题是否已经解决，先关闭 issue 了
