### ISSUE TITLE
修复雪碧图一倍的时候，修改html:font-size != 20px,时，雪碧图位置显示不正确。

### ISSUE THREAD

**Issue by cestrongly** [Tencent/tmt-workflow#132]
# 修改部分/node_modules/gulp-tmtsprite/lib/sprite.js:235
![image](https://user-images.githubusercontent.com/12823509/43262779-e864c932-9113-11e8-9852-c7a32871ca10.png)
修改后：
![image](https://user-images.githubusercontent.com/12823509/43263053-c0505564-9114-11e8-83ae-819b0f893cc0.png)

**Comment by cestrongly** [comment]
## 错误的显示，如图：
![image](https://user-images.githubusercontent.com/12823509/43262969-73df21ba-9114-11e8-8136-c3253e098a9d.png)

**Comment by hzlzh** [comment]
你发的图和代码没有显示成功，建议直接发 github pullrequest 来提交

**Comment by hzlzh** [comment]
雪碧图 和 rem 方案建议不要同时开启，会有兼容问题。
我们的做法是淘汰 雪碧图方案，开启 CDN 对 HTTP2.0 的支持来加速小图片加载

**Comment by cestrongly** [comment]
好的




| |
Cestr
邮箱：cestrmail@163.com
|

Signature is customized by Netease Mail Master

在2018年08月06日 10:32，hzlzh 写道：

雪碧图 和 rem 方案建议不要同时开启，会有兼容问题。
我们的做法是淘汰 雪碧图方案，开启 CDN 对 HTTP2.0 的支持来加速小图片加载
