### ISSUE TITLE
修改项目构建生成时的模板

### ISSUE THREAD

**Issue by xzfd1010** [Tencent/tmt-workflow#133]
目前 项目初始化 时会自己生成一些图片文件、css文件，每次都要清空或修改比较麻烦，请问可以配置成自己的初始化模板么？应该在哪里修改呢？谢谢

**Comment by hzlzh** [comment]
![image](https://user-images.githubusercontent.com/1049575/43693985-9e5e369a-9963-11e8-9dee-1dda38490944.png)
可以，找到 WeFlow.app 右键 - [查看包内容]
解压 templates 里的 zip 然后在重新打包覆盖回来即可
