### ISSUE TITLE
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by zhanyuzhang** [Tencent/tmt-workflow#138]
请问这是什么原因呢？一执行 ` gulp build_dev ` 就报错
![image](https://user-images.githubusercontent.com/12018876/54681860-61ad8100-4b48-11e9-8d84-9a975259b91f.png)

我的gulp版本信息如下：
![image](https://user-images.githubusercontent.com/12018876/54681791-375bc380-4b48-11e9-90a0-51514bae3104.png)

**Comment by zhanyuzhang** [comment]
找到原因了，我的 `node` 版本是 `v10.15.0` , `fs.mkdir()` 方法必须要添加个回调函数的，还有fs.writeFile()也是。比如 `__tasks/common/paseSVG.js` 文件里的 134 行需要改成这样：
![image](https://user-images.githubusercontent.com/12018876/54730149-40897680-4bc2-11e9-8ec3-9d2930a5d04a.png)

**Comment by hzlzh** [comment]
你可以 fork 一份，然后把修改在 https://travis-ci.org/Tencent/tmt-workflow 自动化跑一下 v10.15.0 的版本

**Comment by zhanyuzhang** [comment]
修改前，node10 运行错误：https://travis-ci.org/zhanyuzhang/tmt-workflow/builds/509247241
修改后，运行结果正常：https://travis-ci.org/zhanyuzhang/tmt-workflow/builds/509248633
