### ISSUE TITLE
gulp build_dist之后样式的二级目录都没有了

### ISSUE THREAD

**Issue by ProvenceV** [Tencent/tmt-workflow#140]
![image](https://user-images.githubusercontent.com/19401520/56273665-c3551100-612f-11e9-8774-e14dbaba2604.png)
![image](https://user-images.githubusercontent.com/19401520/56273943-60b04500-6130-11e9-90cb-fac8e6d7a3a6.png)
我在页面中引用了css/style/demo.css，但是build_dist之后css文件夹中原来的二级目录都没有了，所以页面的样式文件就引用不到了。
请问这个问题应该怎么解决，thx。

**Comment by hzlzh** [comment]
由于业务调整，本项目不再更新，感谢大家一直以来的支持。
后续需求会合并到 Feflow 项目进行开发迭代，请移步：
https://github.com/Tencent/feflow
