### ISSUE TITLE
客户端weflow 合并功能并没有让js合并，个人问题？

### ISSUE THREAD

**Issue by shenxiang11** [Tencent/tmt-workflow#57]

**Comment by littledu** [comment]
把你的代码放出来看一下

**Comment by shenxiang11** [comment]
<script src="../js/test.js"></script>
  

开发目录，生产目录均没有见到指定名称的js文件

**Comment by littledu** [comment]
写法没错，可能的情况是 test.js 里面有语法错误，你试试搞个最简单的测试。

**Comment by shenxiang11** [comment]
里面就试一句console.log("Hello World");  注意：我用的GUI 桌面工具

**Comment by JayWii** [comment]
同问，我也遇到了相同的问题

**Comment by shenxiang11** [comment]
@JayWii 
当初就被用户界面所吸引的，说实话不如用webpack这种，当初很小白才用的这个

**Comment by poppop0911** [comment]
html目录里会生成js目录，可能是工具未指定正确dist目录

**Comment by ipengyo** [comment]
同问，js合并压缩有问题，于楼主同样的问题，哎，我是图省事，直接用GUI工具，早知道自己写gulp脚本算了。

**Comment by ipengyo** [comment]
![image](https://cloud.githubusercontent.com/assets/9323722/24837528/ce7bda58-1d68-11e7-9b2e-193f7eec027b.png)


![image](https://cloud.githubusercontent.com/assets/9323722/24837531/d9e568a0-1d68-11e7-9548-891bfc3ca7ee.png)


我想问一下 这个工具不测试的吗？？？？？？？？？？？？？？？？

**Comment by littledu** [comment]
tmt-workflow 没有这个问题，Gui工具存在这个问题，抱歉，我会尽快来修复。
如果你安装没有问题的话，可以直接用tmt-workflow，会更好定制。

**Comment by ipengyo** [comment]
恩恩 我正在使用你们的tom-workflow 但是遇到问题 是npm (cnpm) 下载报错

**Comment by hzlzh** [comment]
@ipengyo 尝试 node 版本 5.10.0
