### ISSUE TITLE
 return binding.readdir(pathModule._makeLong(path));

### ISSUE THREAD

**Issue by xcsweb** [Tencent/tmt-workflow#78]
![image](https://cloud.githubusercontent.com/assets/20693737/19718685/f400ae36-9b98-11e6-9227-4a190c864af8.png)
怎么解决

**Comment by xcsweb** [comment]
在project目录运行也是同样的，我是下载源码来弄的

**Comment by littledu** [comment]
看样子是 node-sass 没装好，你单独安装 `cnpm install gulp-sass` 试试

**Comment by xcsweb** [comment]
@littledu 不行啊，我cnpm install gulp-sass之后还是报这个错

**Comment by 3610cn** [comment]
报同样的错误

**Comment by jiangyanglove** [comment]
经测试， node版本切换到v5.10.0 再install不会报这个错
