### ISSUE TITLE
ejs模板作用范围问题

### ISSUE THREAD

**Issue by petsa** [Tencent/tmt-workflow#88]
ejs模板功能定位是实现什么，发现并不是跟我平时js中使用的的ejs模板。数据是ajax，如何传给tmt的ejs模板？

**Comment by littledu** [comment]
ejs 模版在这里的应用主要是解决我们在 include 一些公用模块时用，比如 header , footer 等等，顺并扩展一些常用片段，如图片占位等。

想跟后端一样使用的话稍显麻烦，需要先定义，如： 
```
<% var name = "littledu" %>
    <div>
    Hello, My Name is <%-name %>
</div>
```
