### ISSUE TITLE
JS合并压缩Bug

### ISSUE THREAD

**Issue by agikoo** [Tencent/tmt-workflow#90]
&lt;!-- build:js ../js/build.js --&gt;
    <script src="../js/aaa.js"></script>
    <script src="../js/bbb.js"></script>
    <script src="../js/ccc.js"></script>
    <script src="../js/ddd.js"></script>
    <script src="../js/eee.js"></script>
    <script src="../js/fff.js"></script>
&lt;!-- endbuild --&gt;
开启 “文件版本 (MD5) 去缓存解决方案”  功能之后，打包生成了例如build.3bd45292.js文件，但是html文件中的js引用是../js/build.js， 而不是../js/build.3bd45292.js

ps：我用的mac版的

**Comment by littledu** [comment]
![image](https://cloud.githubusercontent.com/assets/1784673/24236012/f35f06ba-0fda-11e7-8967-864d3587bab1.png)

我测试了一下正常哦

**Comment by CGerAJ** [comment]
<script src="../js/aaa.js"></script>
<script src="../js/bbb.js"></script>
<script src="../js/ccc.js"></script>
<script src="../js/ddd.js"></script>
<script src="../js/eee.js"></script>
<script src="../js/fff.js"></script>

这个文件是写在什么位置？？？求解答 谢谢

**Comment by littledu** [comment]
？这些文件都必须是存在并且能被正确找到的文件，所以是在根目录下的js目录下

**Comment by ipengyo** [comment]
同遇到这个问题，我发现我的js 根本就没build。

开启了文件版本 (MD5) 去缓存解决方案

还有一个问题，我发现我less文件引入错误，而GUI工具里面点开发，然后一直卡主。根本没有报错

**Comment by hzlzh** [comment]
参考这里：
https://github.com/Tencent/tmt-workflow/blob/master/project/src/html/index.html#L123
